### ISSUE TITLE
Add new datasets and models

### ISSUE THREAD

**Issue by zhangchulanzhang** [encryptogroup/SAFEFL#3]
Hello author, I would like to add new datasets (such as mnist, cifar10, etc.) and new models (such as CNN, ResNet, etc.). What changes do I need to make?

**Comment by Tobias512** [comment]
Hi zhangchulanzhang,
To add new datasets and models, you need to do the following steps. First, everything that has to do with loading and splitting data is done in the ´data_loaders.py´. You need to add cases for your dataset to all three functions ´get_shapes´, ´load_data´, and ´assign_data´. Second, models are loaded via ´get_net´ in ´main.py´. Here you need to add your new model. 
Which dataset and model you want is then controlled by the command line parameters.

**Comment by zhangchulanzhang** [comment]
Okay, thank you for your guidance！
